server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
rateLimitConfiguration:
  refillIntervalMillis: 60_000
  defaultRule:
    maxTokens: 10
    refillRate: 10
  perPath:
    /test:
      maxTokens: 5
      refillRate: 5
    /login:
      maxTokens: 3
      refillRate: 3